const translate = {
  uk: {
    start: "Оберіть мову",
    menu: "Меню",
    record: "🗓 Запис",
    cancelRecord: "❌ Скасувати візит",
    myAccount: "👤 Мій профіль",
    chooseOption: "Оберіть одну з опцій:",
    gratulacje: "🎉 Вітаємо в головному меню!",
    portfolio: "📸 Портфоліо",
    manicure: "💅 Манікюр",
    pedicure: "🦶 Педикюр",
    manicureRemoval: "💅Манікюру зі зміцненням",
    withdraw: "✋ Видалення матеріалу",
    youChose: "ви обрали",
    chose: "Обери",
    choosDate: "Обрати дату",
    time: "Оберіть години",
    timeSet: "Обрані години:",
    isNotFoto: "Поки що немає фото",
    day: "Пн",
    day1: "Вт",
    day2: "Ср",
    day3: "Чт",
    day4: "Пт",
    day5: "Сб",
    day6: "Нд",
    months: [
      "Січень",
      "Лютий",
      "Березень",
      "Квітень",
      "Травень",
      "Червень",
      "Липень",
      "Серпень",
      "Вересень",
      "Жовтень",
      "Листопад",
      "Грудень",
    ],
    askFullName: "✍️ Введіть, будь ласка, своє повне ім’я та прізвище:",
    askPhone:
      "📞 Введіть свій актуальний номер телефону у форматі +48XXXXXXXXX або натисніть «Пропустити»:",
    skip: "Пропустити",
    thanksPhone: "✅ Дякую! Номер збережено.",
    thanksSkip: "✅ Добре, пропускаємо збереження номера.",
    invalidPhone:
      "❌ Невірний формат. Будь ласка, введіть номер у форматі +380XXXXXXXXX.",
    viewAllRecords: "📋 Переглянути всі записи",
    blockDate: "⛔ Заблокувати дату",
    addToPortfolio: "➕ Додати до портфоліо",
    returnMenu: "⬅ Повернутись до головного меню",
    notNumber: "Невідомий номер",
    name: "Ім’я",
    phone: "Телефон",
    service: "Послуга",
    date: "Дата",
    time: "Час",
    noName: "Немає імені",
    noPhone: "Немає телефону",
    noService: "Немає послуги",
    noDate: "Немає дати",
    noTime: "Немає часу",
    noBooking: "У вас немає активних записів",
    profil: "Ваш профіль",
    notRecord: "❌ Не можна вибрати час у минулому.",
    backToMainMenu: "⬅️ Повернутися до меню",
    bookingCancelled: "Ваш запис скасовано.",
    noBooking: "У вас немає активного запису.",
    allActiveRecords: "Усі активні записи",
    noActiveRecords: "Немає активних записів.",
    invalidDate: "❌ Не можна вибрати минулу дату.",
    notTime: "⛔ Ця година недоступна.",
  },

  pl: {
    notTime: "⛔ Ta godzina jest niedostępna.",
    invalidDate: "❌ Nie można wybrać daty z przeszłości.",
    isNotFoto: "Jeszcze nie ma zdjęć.",
    start: "Wybierz język",
    menu: "Menu",
    record: "🗓 Rezerwacja",
    cancelRecord: "❌ Anuluj rejestrację",
    myAccount: "👤 Moje konto",
    chooseOption: "Wybierz jedną z opcji:",
    gratulacje: "🎉 Witamy! Jesteś w menu głównym",
    portfolio: "📸 Portfolio",
    manicure: "💅 Manicure",
    pedicure: "🦶 Pedicure",
    manicureRemoval: "💅Manicure ze wzmocnieniem",
    withdraw: "✋ Usuwanie materiału",
    youChose: "Wybrałeś",
    chose: "Wybierz",
    choosDate: "Wybierz datę",
    time: "Wybierz godziny:",
    timeSet: "Wybrane godziny:",
    day: "Pon",
    day1: "Wt",
    day2: "Śr",
    day3: "Czw",
    day4: "Pt",
    day5: "Sob",
    day6: "Nd",
    months: [
      "Styczeń",
      "Luty",
      "Marzec",
      "Kwiecień",
      "Maj",
      "Czerwiec",
      "Lipiec",
      "Sierpień",
      "Wrzesień",
      "Październik",
      "Listopad",
      "Grudzień",
    ],
    askFullName: "✍️ Wpisz swoje pełne imię i nazwisko:",
    askPhone:
      "📞 Wpisz swój aktualny numer telefonu w formacie międzynarodowym (np. +48XXXXXXXXX) lub kliknij „Pomiń”:",
    skip: "Pomiń",
    thanksPhone: "✅ Dziękujemy! Numer zapisany.",
    thanksSkip: "✅ W porządku, pomijamy zapis numeru.",
    invalidPhone:
      "❌ Nieprawidłowy format. Wprowadź numer w formacie międzynarodowym (np. +48XXXXXXXXX).",
    acceptShare: "✅ Tak, udostępnij",
    skipShare: "❌ Nie, pomiń",
    sendPhone: "📱 Kliknij poniższy przycisk, aby udostępnić numer",
    sharePhone: "📤 Udostępnij numer",
    viewAllRecords: "📋 Zobacz wszystkie rezerwacje",
    blockDate: "⛔ Zablokuj datę",
    addToPortfolio: "➕ Dodaj do portfolio",
    returnMenu: "⬅ Powrót do menu głównego",
    profileInfo: "Twój profil",
    name: "Imię",
    phone: "Telefon",
    service: "Usługa",
    date: "Data",
    time: "Godzina",
    noName: "Brak imienia",
    noPhone: "Brak numeru telefonu",
    noService: "Brak usługi",
    noDate: "Brak daty",
    noTime: "Brak godziny",
    noBooking: "Nie masz aktywnych rezerwacji",
    profil: "Twój profil",
    notRecord: "❌Nie można wybrać czasu z przeszłości.",
    backToMainMenu: "⬅️ Wróć do menu",
    bookingCancelled: "Twoje zgłoszenie zostało anulowane.",
    noBooking: "Nie masz aktywnego konta.",
    allActiveRecords: "Wszystkie aktywne rezerwacje",
    noActiveRecords: "Brak aktywnych rezerwacji.",
  },
};

module.exports = translate;
